# Generated by Django 3.1.2 on 2020-10-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='id',
        ),
        migrations.AlterField(
            model_name='vessel',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Vessel code'),
        ),
    ]
