# Generated by Django 3.1.2 on 2020-10-12 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201012_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Equipment code')),
                ('name', models.CharField(max_length=50, verbose_name='Equipment name')),
                ('location', models.CharField(max_length=50, verbose_name='Equipment location')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20, verbose_name='Equipment status')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vessel')),
            ],
        ),
    ]
