# Generated by Django 3.1.2 on 2020-10-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='api.vessel'),
        ),
    ]
